# Specify the line length that the printer will wrap on.
printWidth: 1000000

# Specify the number of spaces per indentation-level.
tabWidth: 2

# Indent lines with tabs instead of spaces.
useTabs: false

# Print semicolons at the ends of statements.
semi: true

# Use single quotes instead of double quotes.
singleQuote: false

# Change when properties in objects are quoted.
quoteProps: "as-needed"

# Use single quotes instead of double quotes in JSX.
jsxSingleQuote: false

# Print trailing commas wherever possible in multi-line comma-separated syntactic structures. (A single-line array, for example, never gets trailing commas.)
trailingComma: "none"

# Print spaces between brackets in object literals.
bracketSpacing: true

# Configure how Prettier wraps object literals when they could fit on one line or span multiple lines.
objectWrap: "preserve"

# Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).
bracketSameLine: true

# Include parentheses around a sole arrow function parameter.
arrowParens: "avoid"

# Prettier can restrict itself to only format files that contain a special comment, called a pragma, at the top of the file. This is very useful when gradually transitioning large, unformatted codebases to Prettier.
requirePragma: false

# Prettier can insert a special @format marker at the top of files specifying that the file has been formatted with Prettier. This works well when used in tandem with the --require-pragma option. If there is already a docblock at the top of the file then this option will add a newline to it with the @format marker.
insertPragma: false

# Prettier can allow individual files to opt out of formatting if they contain a special comment, called a pragma, at the top of the file.
checkIgnorePragma: true

# By default, Prettier will not change wrapping in markdown text since some services use a linebreak-sensitive renderer, e.g. GitHub comments and BitBucket. To have Prettier wrap prose to the print width, change this option to "always". If you want Prettier to force all prose blocks to be on a single line and rely on editor/viewer soft wrapping instead, you can use "never".
proseWrap: "preserve"

# Specify the global whitespace sensitivity for HTML, Vue, Angular, and Handlebars. See whitespace-sensitive formatting for more info.
htmlWhitespaceSensitivity: "css"

# Whether or not to indent the code inside <script> and <style> tags in Vue files.
vueIndentScriptAndStyle: true

# For historical reasons, there exist two common flavors of line endings in text files. That is \n (or LF for Line Feed) and \r\n (or CRLF for Carriage Return + Line Feed). The former is common on Linux and macOS, while the latter is prevalent on Windows. Some details explaining why it is so can be found on Wikipedia.
# All modern text editors in all operating systems are able to correctly display line endings when \n (LF) is used. However, old versions of Notepad for Windows will visually squash such lines into one as they can only deal with \r\n (CRLF).
endOfLine: "lf"

# Control whether Prettier formats quoted code embedded in the file.
# When Prettier identifies cases where it looks like you've placed some code it knows how to format within a string in another file, like in a tagged template in JavaScript with a tag named html or in code blocks in Markdown, it will by default try to format that code.
embeddedLanguageFormatting: "auto"

# Enforce single attribute per line in HTML, Vue, and JSX.
singleAttributePerLine: false